const express = require('express');
const _ = require('lodash');

const router = express.Router();

const Products = require('../../models/productsModel');
const Flavours = require('../../models/flavoursAndDrinks');
const Marts = require('../../models/martsModel');

router.post('/allProducts', async (req, res) => {
  try {
    const { martId } = req.body;
    const allCategories = [];
    let finalData = [];

    const categories = await Products.find({ martId })
      .sort({
        category: 1,
      })
      .select('category');
    const business = await Marts.findById({ _id: martId }).select('shopType');

    await Promise.all(
      categories.map(c => {
        if (!allCategories.includes(c.category)) {
          allCategories.push(c.category);
        }
        return allCategories;
      })
    );

    if (business.shopType === 'restaurant') {
      await Promise.all(
        allCategories.map(async ac => {
          const query = {
            category: ac,
            martId,
          };

          const products = await Products.find(query).sort({ productName: 1 });

          await Promise.all(
            products.map(async p => {
              if (p.type === 'deal') {
                const flavoursAndDrinks = await Flavours.findOne({
                  martId,
                }).select('flavours');
                p.flavours = flavoursAndDrinks.flavours;
              }

              if (p.drinks === true) {
                const flavoursAndDrinks = await Flavours.findOne({
                  martId,
                }).select('drinks');
                p.allDrinks = flavoursAndDrinks.drinks;
              }
            })
          );

          const data = {
            category: ac,
            data: products,
          };

          await Promise.resolve(data);
          await Promise.resolve(finalData.push(data));
        })
      );

      finalData = _.orderBy(finalData, ['category'], ['asc']);

      return res.json({
        status: '200',
        data: finalData,
      });
    }

    await Promise.all(
      allCategories.map(async ac => {
        const query = {
          category: ac,
          martId,
        };

        const martProducts = await Products.find(query).sort({
          productName: 1,
        });

        const data = {
          category: ac,
          data: martProducts,
        };

        await Promise.resolve(data);
        await Promise.resolve(finalData.push(data));
      })
    );

    finalData = _.orderBy(finalData, ['category'], ['asc']);

    return res.json({
      status: '200',
      data: finalData,
    });
  } catch (err) {
    return res.json({
      status: '404',
      msg: `Looks like something went wrong on our side. Sorry for the inconvenience.`,
    });
  }
});

router.post('/deleteProduct/', async (req, res) => {
  try {
    await Products.findByIdAndDelete({ _id: req.body.productId });

    return res.json({
      status: '200',
      msg: 'Product deleted successfully',
    });
  } catch (err) {
    return res.json({
      status: '404',
      error: err.toString(),
      msg: `Looks like something went wrong on our side. Sorry for the inconvenience.`,
    });
  }
});

router.get('/addBulkProducts/', async (req, res) => {
  try {
    await Products.insertMany([
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Peri Peri  Chicken + Fries (Extra Hot)',
        category: 'Peri Peri Special',
        quantity: 'Quarter',
        price: '250',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Peri Peri  Chicken + Fries ( Hot)',
        category: 'Peri Peri Special',
        quantity: 'Quarter',
        price: '250',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Peri Peri  Chicken + Fries (Mild)',
        category: 'Peri Peri Special',
        quantity: 'Quarter',
        price: '250',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Peri Peri Chicken + Fries (Lemon & Herb)',
        category: 'Peri Peri Special',
        quantity: 'Quarter',
        price: '250',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Peri Peri  Chicken + Fries (Extra Hot)',
        category: 'Peri Peri Special',
        quantity: 'Half',
        price: '500',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Peri Peri  Chicken + Fries ( Hot)',
        category: 'Peri Peri Special',
        quantity: 'Half',
        price: '500',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Peri Peri  Chicken + Fries (Mild)',
        category: 'Peri Peri Special',
        quantity: 'Half',
        price: '500',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Peri Peri  Chicken + Fries (Lemon & Herb)',
        category: 'Peri Peri Special',
        quantity: 'Half',
        price: '500',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Peri Peri  Chicken + Fries (Extra Hot)',
        category: 'Peri Peri Special',
        quantity: 'Full',
        price: '1000',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Peri Peri  Chicken + Fries ( Hot)',
        category: 'Peri Peri Special',
        quantity: 'Full',
        price: '1000',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Peri Peri  Chicken + Fries (Mild)',
        category: 'Peri Peri Special',
        quantity: 'Full',
        price: '1000',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Peri Peri  Chicken + Fries (Lemon & Herb)',
        category: 'Peri Peri Special',
        quantity: 'Full',
        price: '1000',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Peri Peri Special Burger (Extra Hot)',
        category: 'Peri Peri Special',
        quantity: '',
        price: '300',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Peri Peri Special Burger (Hot)',
        category: 'Peri Peri Special',
        quantity: '',
        price: '300',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Peri Peri Special Burger (Mild)',
        category: 'Peri Peri Special',
        quantity: '',
        price: '300',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Peri Peri Special Burger (Lemon & Herb)',
        category: 'Peri Peri Special',
        quantity: '',
        price: '300',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Peri Peri Wings (Extra Hot)',
        category: 'Peri Peri Special',
        quantity: '5 Pcs',
        price: '200',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Peri Peri Wings (Hot)',
        category: 'Peri Peri Special',
        quantity: '5 Pcs',
        price: '200',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Peri Peri Wings (Mild)',
        category: 'Peri Peri Special',
        quantity: '5 Pcs',
        price: '200',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Peri Peri Wings (Lemon & Herb)',
        category: 'Peri Peri Special',
        quantity: '5 Pcs',
        price: '200',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Peri Peri Wings (Extra Hot)',
        category: 'Peri Peri Special',
        quantity: '10 Pcs',
        price: '400',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Peri Peri Wings (Hot)',
        category: 'Peri Peri Special',
        quantity: '10 Pcs',
        price: '400',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Peri Peri Wings (Mild)',
        category: 'Peri Peri Special',
        quantity: '10 Pcs',
        price: '400',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Peri Peri Wings (Lemon & Herb)',
        category: 'Peri Peri Special',
        quantity: '10 Pcs',
        price: '400',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Student Deal',
        category: 'Deals',
        quantity:
          'Half Peri Peri Chicken + 5Pcs Wings +  1 Grill Burger + 1 Mighty Zingar + 1 Drink + 1 Fries',
        price: '1200',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'true',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Tikka Pizza',
        category: 'Pizza',
        quantity: 'Small',
        price: '300',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Tikka Pizza',
        category: 'Pizza',
        quantity: 'Medium',
        price: '600',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Tikka Pizza',
        category: 'Pizza',
        quantity: 'Large',
        price: '900',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Tikka Pizza',
        category: 'Pizza',
        quantity: 'Family',
        price: '1290',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Fajita Pizza',
        category: 'Pizza',
        quantity: 'Small',
        price: '300',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Fajita Pizza',
        category: 'Pizza',
        quantity: 'Medium',
        price: '600',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Fajita Pizza',
        category: 'Pizza',
        quantity: 'Large',
        price: '900',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Fajita Pizza',
        category: 'Pizza',
        quantity: 'Family',
        price: '1290',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Mallai Pizza',
        category: 'Pizza',
        quantity: 'Small',
        price: '300',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Mallai Pizza',
        category: 'Pizza',
        quantity: 'Medium',
        price: '650',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Mallai Pizza',
        category: 'Pizza',
        quantity: 'Large',
        price: '950',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Mallai Pizza',
        category: 'Pizza',
        quantity: 'Family',
        price: '1350',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Ranch Pizza',
        category: 'Pizza',
        quantity: 'Small',
        price: '350',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Ranch Pizza',
        category: 'Pizza',
        quantity: 'Medium',
        price: '700',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Ranch Pizza',
        category: 'Pizza',
        quantity: 'Large',
        price: '1000',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Ranch Pizza',
        category: 'Pizza',
        quantity: 'Family',
        price: '1400',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Hot & Spicy Pizza',
        category: 'Pizza',
        quantity: 'Small',
        price: '300',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Hot & Spicy Pizza',
        category: 'Pizza',
        quantity: 'Medium',
        price: '600',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Hot & Spicy Pizza',
        category: 'Pizza',
        quantity: 'Large',
        price: '900',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Hot & Spicy Pizza',
        category: 'Pizza',
        quantity: 'Family',
        price: '1290',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Legend BBQ Pizza',
        category: 'Pizza',
        quantity: 'Small',
        price: '350',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Legend BBQ Pizza',
        category: 'Pizza',
        quantity: 'Medium',
        price: '650',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Legend BBQ Pizza',
        category: 'Pizza',
        quantity: 'Large',
        price: '950',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Legend BBQ Pizza',
        category: 'Pizza',
        quantity: 'Family',
        price: '1350',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Super Supreme Pizza',
        category: 'Pizza',
        quantity: 'Small',
        price: '350',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Super Supreme Pizza',
        category: 'Pizza',
        quantity: 'Medium',
        price: '650',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Super Supreme Pizza',
        category: 'Pizza',
        quantity: 'Large',
        price: '950',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Super Supreme Pizza',
        category: 'Pizza',
        quantity: 'Family',
        price: '1350',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Tex Mex Pizza',
        category: 'Pizza',
        quantity: 'Small',
        price: '400',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Tex Mex Pizza',
        category: 'Pizza',
        quantity: 'Medium',
        price: '700',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Tex Mex Pizza',
        category: 'Pizza',
        quantity: 'Large',
        price: '950',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Tex Mex Pizza',
        category: 'Pizza',
        quantity: 'Family',
        price: '1350',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Kababish / Behari Pizza',
        category: 'Pizza',
        quantity: 'Small',
        price: '400',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Kababish / Behari Pizza',
        category: 'Pizza',
        quantity: 'Medium',
        price: '800',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Kababish / Behari Pizza',
        category: 'Pizza',
        quantity: 'Large',
        price: '1200',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Kababish / Behari Pizza',
        category: 'Pizza',
        quantity: 'Family',
        price: '1500',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Chef Special Pizza',
        category: 'Pizza',
        quantity: 'Small',
        price: '400',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Chef Special Pizza',
        category: 'Pizza',
        quantity: 'Medium',
        price: '800',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Chef Special Pizza',
        category: 'Pizza',
        quantity: 'Large',
        price: '1200',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Chef Special Pizza',
        category: 'Pizza',
        quantity: 'Family',
        price: '1500',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Small Pizza Deal',
        category: 'Pizza Deals',
        quantity: 'Buy 1 Small Pizza Get 1 Small Pizza Free',
        price: '490',
        net: '0',
        count: '0',
        type: 'deal',
        drinks: 'false',
        sizes: [
          {
            value: 'Small 1',
          },
          {
            value: 'Small 2',
          },
        ],
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Medium Pizza Deal',
        category: 'Pizza Deals',
        quantity: 'Buy 1 Medium Pizza Get 1 Medium Pizza Free',
        price: '1150',
        net: '0',
        count: '0',
        type: 'deal',
        drinks: 'false',
        sizes: [
          {
            value: 'Medium 1',
          },
          {
            value: 'Medium 2',
          },
        ],
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Large Pizza Deal',
        category: 'Pizza Deals',
        quantity: 'Buy 1 Large Pizza Get 1 Large Pizza Free',
        price: '1650',
        net: '0',
        count: '0',
        type: 'deal',
        drinks: 'false',
        sizes: [
          {
            value: 'Large 1',
          },
          {
            value: 'Large 2',
          },
        ],
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Family Pizza Deal',
        category: 'Pizza Deals',
        quantity: 'Buy 1 Family Pizza Get 1 Family Pizza Free',
        price: '2590',
        net: '0',
        count: '0',
        type: 'deal',
        drinks: 'false',
        sizes: [
          {
            value: 'Family 1',
          },
          {
            value: 'Family 2',
          },
        ],
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Mighty Zinger',
        category: 'Burgers',
        quantity: '',
        price: '150',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Cardan Blue',
        category: 'Burgers',
        quantity: '',
        price: '200',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Chicken Crunchy Burger',
        category: 'Burgers',
        quantity: '',
        price: '150',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Chicken Huwaiven Burger',
        category: 'Burgers',
        quantity: '',
        price: '225',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Big Eleven Burger',
        category: 'Burgers',
        quantity: '',
        price: '200',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Chicken Signature Burger',
        category: 'Burgers',
        quantity: '',
        price: '120',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Chicken College Burger',
        category: 'Burgers',
        quantity: '',
        price: '150',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Mighty Zinger + Fries + Reg Drink',
        category: 'Burger Meal',
        quantity: '',
        price: '250',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'true',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Cardan Blue + Fries + Reg Drink',
        category: 'Burger Meal',
        quantity: '',
        price: '300',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'true',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Chicken Crunchy Burger + Fries + Reg Drink',
        category: 'Burger Meal',
        quantity: '',
        price: '250',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'true',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Chicken Huwaiven Burger + Fries + Reg Drink',
        category: 'Burger Meal',
        quantity: '',
        price: '350',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'true',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Big Eleven Burger + Fries + Reg Drink',
        category: 'Burger Meal',
        quantity: '',
        price: '300',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'true',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Chicken Signature Burger + Fries + Reg Drink',
        category: 'Burger Meal',
        quantity: '',
        price: '200',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'true',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Chicken College Burger + Fries + Reg Drink',
        category: 'Burger Meal',
        quantity: '',
        price: '150',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'true',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Chicken Shawarma',
        category: 'Shawarma',
        quantity: '',
        price: '90',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Mashroom Shawarma',
        category: 'Shawarma',
        quantity: '',
        price: '130',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Zatoon Shawarma',
        category: 'Shawarma',
        quantity: '',
        price: '130',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Chicken Paratha',
        category: 'Paratha',
        quantity: '',
        price: '120',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Mashroom Paratha',
        category: 'Paratha',
        quantity: '',
        price: '150',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Zatoon Paratha',
        category: 'Paratha',
        quantity: '',
        price: '150',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Fried Chicken Piece',
        category: 'Fried Cicken',
        quantity: '',
        price: '120',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: '2 Chicken pieces + Reg Drink + 1 Fries',
        category: 'Fried Cicken',
        quantity: '',
        price: '320',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: '3 Chicken pieces + 1/2 Ltr Drink + Regular Fries',
        category: 'Fried Cicken',
        quantity: '',
        price: '430',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: '9 Chicken pieces + 1.5 Ltr Drink + Family Fries',
        category: 'Fried Cicken',
        quantity: '',
        price: '1090',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: '5 Pcs + 1 Reg Drink',
        category: 'Fried Cicken',
        quantity: '',
        price: '150',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: '10 Pcs + 1/2 Drink',
        category: 'Fried Cicken',
        quantity: '',
        price: '300',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Chicken Nuggets',
        category: 'Fried Cicken',
        quantity: '',
        price: '150',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Chicken Nuggets',
        category: 'Fried Cicken',
        quantity: '',
        price: '300',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Small Deal',
        category: 'Deals',
        quantity: '1 Peri Peri + Mini Zinger + Half Ltr Drink + Regualr Fries',
        price: '450',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'true',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Small Deal 2',
        category: 'Deals',
        quantity: '1 Small Pizza + 2 Fried Chicken Piece + Half ltr Drink',
        price: '500',
        net: '0',
        count: '0',
        type: 'deal',
        drinks: 'true',
        sizes: [
          {
            value: 'Small',
          },
        ],
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Small Deal 3',
        category: 'Deals',
        quantity:
          'Chicken + Mashroom + Zaitoon Shawarma + Regular Fries + 1 Ltr Drink',
        price: '480',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'true',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Special Deal',
        category: 'Deals',
        quantity:
          '1 Zinger Burger + 1 Small Pizza + 5 Hot Wings + 1 Peri Peri Chicken + 1 Regular Fries + 1.5 Ltr Drink',
        price: '999',
        net: '0',
        count: '0',
        type: 'deal',
        drinks: 'true',
        sizes: [
          {
            value: 'Small',
          },
        ],
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Special Deal 2',
        category: 'Deals',
        quantity:
          '1 Crunch + 1 Cordan + 1 Hawaien Burger + 5 Peri Peri Wings + 1 Small Pizza + 1 Ltr Drink + 1 Family Fries',
        price: '1199',
        net: '0',
        count: '0',
        type: 'deal',
        drinks: 'true',
        sizes: [
          {
            value: 'Small',
          },
        ],
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Special Deal 3',
        category: 'Deals',
        quantity:
          '3 Pcs Fried Chicken + 10 Hot Wings + 5 Nuggets + 1 Ltr Drink + 1 Regular Fries',
        price: '799',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'true',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Special Deal 4',
        category: 'Deals',
        quantity:
          '1 Medium Pizza + 1/2 Kg Salad + 1/2 Peri Peri Chicken + Large Fries + 1.5 Ltr Drink',
        price: '1499',
        net: '0',
        count: '0',
        type: 'deal',
        drinks: 'true',
        sizes: [
          {
            value: 'Medium',
          },
        ],
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Fried Chicken Deal',
        category: 'Deals',
        quantity: '5 Nuggets + 5 Wings + 1 Regular Fries + 500 ml Drink',
        price: '350',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'true',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Fried Chicken Deal 2',
        category: 'Deals',
        quantity:
          '2 Pcs Fried Chicken + 5 Hot Wings + 1 Regular Fries + 500 ml Drink',
        price: '450',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'true',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Combo Deal',
        category: 'Deals',
        quantity:
          '1 Family Pizza + 10 Hot Wings + 3 Chicken Pieces + 3 Mighty Zinger + 1.5 Ltr Drink + Family Fries',
        price: '2300',
        net: '0',
        count: '0',
        type: 'deal',
        drinks: 'true',
        sizes: [
          {
            value: 'Family',
          },
        ],
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Halt Liter Coke',
        category: 'Drinks',
        quantity: '',
        price: '50',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: '1 Liter Coke',
        category: 'Drinks',
        quantity: '',
        price: '70',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: '1.5 Liter Coke',
        category: 'Drinks',
        quantity: '',
        price: '100',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: 'Half Liter Sprite',
        category: 'Drinks',
        quantity: '',
        price: '50',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: '1 Liter Sprite',
        category: 'Drinks',
        quantity: '',
        price: '70',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
      {
        martId: '5ed8c1afab287d184e210b89',
        productName: '1.5 Liter Sprite',
        category: 'Drinks',
        quantity: '',
        price: '100',
        net: '0',
        count: '0',
        type: 'single',
        drinks: 'false',
      },
    ]);

    return res.json({
      status: '200',
      msg: 'Product added successfully',
    });
  } catch (err) {
    return res.json({
      status: '404',
      error: err.toString(),
      msg: `Looks like something went wrong on our side. Sorry for the inconvenience.`,
    });
  }
});

module.exports = router;
