const express = require('express');
const _ = require('lodash');

const router = express.Router();

const Products = require('../../models/productsModel');
const Flavours = require('../../models/flavoursAndDrinks');
const Marts = require('../../models/martsModel');

router.post('/allProducts', async (req, res) => {
  try {
    const { martId } = req.body;
    const allCategories = [];
    let finalData = [];

    const categories = await Products.find({ martId })
      .sort({
        category: 1,
      })
      .select('category');

    const business = await Marts.findById({ _id: martId }).select('shopType');

    await Promise.all(
      categories.map(c => {
        if (!allCategories.includes(c.category)) {
          allCategories.push(c.category);
        }
        return allCategories;
      })
    );

    if (business.shopType === 'restaurant') {
      await Promise.all(
        allCategories.map(async ac => {
          const query = {
            category: ac,
            martId,
            available: 'in stock',
          };

          const products = await Products.find(query).sort({ productName: 1 });

          await Promise.all(
            products.map(async p => {
              if (
                p.type === 'deal' &&
                (p.regular === undefined || null || false)
              ) {
                const flavoursAndDrinks = await Flavours.findOne({
                  martId,
                }).select('flavours');
                p.flavours = flavoursAndDrinks.flavours;
              }

              if (p.type === 'deal' && p.regular === true) {
                const flavoursAndDrinks = await Flavours.findOne({
                  martId,
                }).select('regularFlavours');
                p.flavours = flavoursAndDrinks.regularFlavours;
              }

              if (p.drinks === true) {
                const flavoursAndDrinks = await Flavours.findOne({
                  martId,
                }).select('drinks');
                p.allDrinks = flavoursAndDrinks.drinks;
              }
            })
          );

          const data = {
            category: ac,
            data: products,
          };

          await Promise.resolve(data);
          await Promise.resolve(finalData.push(data));
        })
      );

      finalData = _.orderBy(finalData, ['category'], ['asc']);

      return res.json({
        status: '200',
        data: finalData,
      });
    }

    await Promise.all(
      allCategories.map(async ac => {
        const query = {
          category: ac,
          martId,
          available: 'in stock',
        };

        const martProducts = await Products.find(query).sort({
          productName: 1,
        });

        const data = {
          category: ac,
          data: martProducts,
        };

        await Promise.resolve(data);
        await Promise.resolve(finalData.push(data));
      })
    );

    finalData = _.orderBy(finalData, ['category'], ['asc']);

    return res.json({
      status: '200',
      data: finalData,
    });
  } catch (err) {
    return res.json({
      status: '404',
      msg: `Looks like something went wrong on our side. Sorry for the inconvenience.`,
    });
  }
});

router.post('/allRestaurantProducts', async (req, res) => {
  try {
    const { martId } = req.body;
    const allCategories = [];
    let finalData = [];

    const categories = await Products.find({ martId })
      .sort({
        category: 1,
      })
      .select('category');

    await Promise.all(
      categories.map(c => {
        if (!allCategories.includes(c.category)) {
          allCategories.push(c.category);
        }
        return allCategories;
      })
    );

    await Promise.all(
      allCategories.map(async ac => {
        const query = {
          category: ac,
          martId,
        };

        const products = await Products.find(query).sort({ productName: 1 });

        const data = {
          category: ac,
          data: products,
        };

        await Promise.resolve(data);
        await Promise.resolve(finalData.push(data));
      })
    );

    finalData = _.orderBy(finalData, ['category'], ['asc']);

    return res.json({
      status: '200',
      data: finalData,
    });
  } catch (err) {
    return res.json({
      status: '404',
      msg: `Looks like something went wrong on our side. Sorry for the inconvenience.`,
    });
  }
});

router.post('/allCategories', async (req, res) => {
  try {
    const { martId } = req.body;
    const allCategories = [];

    const categories = await Products.find({ martId })
      .sort({
        category: 1,
      })
      .select('category');

    await Promise.all(
      categories.map(c => {
        if (!allCategories.includes(c.category)) {
          allCategories.push(c.category);
        }
        return allCategories;
      })
    );

    return res.json({
      status: '200',
      data: allCategories,
    });
  } catch (err) {
    return res.json({
      status: '404',
      msg: `Looks like something went wrong on our side. Sorry for the inconvenience.`,
    });
  }
});

router.post('/productAvailability', async (req, res) => {
  try {
    const { productId } = req.body;

    await Products.findByIdAndUpdate(productId, { $set: req.body });

    return res.json({
      status: '200',
      msg: 'Product status updated',
    });
  } catch (err) {
    return res.json({
      status: '404',
      error: err.toString(),
      msg: `Looks like something went wrong on our side. Sorry for the inconvenience.`,
    });
  }
});

router.post('/allMartProducts', async (req, res) => {
  try {
    const { martId, type } = req.body;
    let products;

    if (type === 'admin') {
      products = await Products.find({ martId }).sort({ productName: 1 });
    } else {
      products = await Products.find({ martId, available: 'in stock' }).sort({
        productName: 1,
      });
    }

    return res.json({
      status: '200',
      data: products,
    });
  } catch (err) {
    return res.json({
      status: '404',
      error: err.toString(),
      msg: `Looks like something went wrong on our side. Sorry for the inconvenience.`,
    });
  }
});

/* router.get('/addBulkProducts/', async (req, res) => {
  try {
    await Products.insertMany([
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Deal 1',
        category: 'Deals',
        quantity: '1 P.P Regular Pizza + 1 Reg Drink',
        price: '290',
        net: '0',
        count: '0',
        type: 'deal',
        drinks: true,
        regular: true,
        lunchTimeStart: '',
        lunchTimeEnd: '',
        sizes: [{ value: 'Personal Pan' }],
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Chicken Tikka',
        category: 'Regular Pizza',
        quantity: 'Personal Pan',
        price: '260',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Chicken Tikka',
        category: 'Regular Pizza',
        quantity: 'Small',
        price: '320',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Chicken Tikka',
        category: 'Regular Pizza',
        quantity: 'Medium',
        price: '650',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Chicken Tikka',
        category: 'Regular Pizza',
        quantity: 'Large',
        price: '900',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Chicken Tikka',
        category: 'Regular Pizza',
        quantity: 'Family',
        price: '1400',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Chicken Fajita',
        category: 'Regular Pizza',
        quantity: 'Personal Pan',
        price: '260',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Chicken Fajita',
        category: 'Regular Pizza',
        quantity: 'Small',
        price: '320',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Chicken Fajita',
        category: 'Regular Pizza',
        quantity: 'Medium',
        price: '650',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Chicken Fajita',
        category: 'Regular Pizza',
        quantity: 'Large',
        price: '900',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Chicken Fajita',
        category: 'Regular Pizza',
        quantity: 'Family',
        price: '1400',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Pickle Pizza',
        category: 'Regular Pizza',
        quantity: 'Personal Pan',
        price: '260',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Pickle Pizza',
        category: 'Regular Pizza',
        quantity: 'Small',
        price: '320',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Pickle Pizza',
        category: 'Regular Pizza',
        quantity: 'Medium',
        price: '650',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Pickle Pizza',
        category: 'Regular Pizza',
        quantity: 'Large',
        price: '900',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Pickle Pizza',
        category: 'Regular Pizza',
        quantity: 'Family',
        price: '1400',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Sausage Pizza',
        category: 'Regular Pizza',
        quantity: 'Personal Pan',
        price: '260',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Sausage Pizza',
        category: 'Regular Pizza',
        quantity: 'Small',
        price: '320',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Sausage Pizza',
        category: 'Regular Pizza',
        quantity: 'Medium',
        price: '650',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Sausage Pizza',
        category: 'Regular Pizza',
        quantity: 'Large',
        price: '900',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Sausage Pizza',
        category: 'Regular Pizza',
        quantity: 'Family',
        price: '1400',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Peproni Pizza',
        category: 'Regular Pizza',
        quantity: 'Personal Pan',
        price: '260',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Peproni Pizza',
        category: 'Regular Pizza',
        quantity: 'Small',
        price: '320',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Peproni Pizza',
        category: 'Regular Pizza',
        quantity: 'Medium',
        price: '650',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Peproni Pizza',
        category: 'Regular Pizza',
        quantity: 'Large',
        price: '900',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Peproni Pizza',
        category: 'Regular Pizza',
        quantity: 'Family',
        price: '1400',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Vege Lover Pizza',
        category: 'Regular Pizza',
        quantity: 'Personal Pan',
        price: '260',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Vege Lover Pizza',
        category: 'Regular Pizza',
        quantity: 'Small',
        price: '320',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Vege Lover Pizza',
        category: 'Regular Pizza',
        quantity: 'Medium',
        price: '650',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Vege Lover Pizza',
        category: 'Regular Pizza',
        quantity: 'Large',
        price: '900',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Vege Lover Pizza',
        category: 'Regular Pizza',
        quantity: 'Family',
        price: '1400',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Flame Cheese Lover',
        category: 'Regular Pizza',
        quantity: 'Personal Pan',
        price: '260',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Malai Boti Crust',
        category: 'Stuffed Crust Pizza',
        quantity: 'Small',
        price: '390',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Junior Zinger',
        category: 'Burgers',
        quantity: '',
        price: '140',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Flames Combo 1',
        category: 'Flames Combo',
        quantity: '1 Junior Zinger + 1 Pc Chicken + 1 Reg Fries + 1 Reg Drink',
        price: '390',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Reggy Burger',
        category: 'Burgers',
        quantity: '',
        price: '140',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Flames Combo 2',
        category: 'Flames Combo',
        quantity: '2 Pc Chicken + 1 Reg Drink',
        price: '310',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Zinger Burger',
        category: 'Burgers',
        quantity: '',
        price: '240',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Flames Combo 3',
        category: 'Flames Combo',
        quantity: '10 Hot Wings + 1 Reg Drink',
        price: '350',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Beef Burger',
        category: 'Burgers',
        quantity: '',
        price: '199',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Flames Combo 4',
        category: 'Flames Combo',
        quantity: '10 Peri Peri Wings + 1 Reg Drink',
        price: '370',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Peri Peri Burger',
        category: 'Burgers',
        quantity: '',
        price: '299',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Chapli Burger',
        category: 'Burgers',
        quantity: '',
        price: '160',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Grilled Burger',
        category: 'Burgers',
        quantity: '',
        price: '270',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Chicken Shawarma',
        category: 'Shawarmas',
        quantity: '',
        price: '120',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Zinger Shawarma',
        category: 'Shawarmas',
        quantity: '',
        price: '160',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Behari Kabab Paratha',
        category: 'Parathas',
        quantity: '',
        price: '150',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Chicken Paratha',
        category: 'Parathas',
        quantity: '',
        price: '130',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Grilled Paratha',
        category: 'Parathas',
        quantity: '',
        price: '160',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Deal 2',
        category: 'Deals',
        quantity: '1 Medium Regular Pizza + 1 Liter Drink',
        price: '720',
        net: '0',
        count: '0',
        type: 'deal',
        drinks: true,
        regular: true,
        lunchTimeStart: '',
        lunchTimeEnd: '',
        sizes: [{ value: 'Medium' }],
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Deal 3',
        category: 'Deals',
        quantity: '1 Large Regular Pizza + 1.5 Liter Drink',
        price: '999',
        net: '0',
        count: '0',
        type: 'deal',
        drinks: true,
        regular: true,
        lunchTimeStart: '',
        lunchTimeEnd: '',
        sizes: [{ value: 'Large' }],
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Deal 4',
        category: 'Deals',
        quantity: '1 Family Regular Pizza + 1.5 Liter Drink',
        price: '1499',
        net: '0',
        count: '0',
        type: 'deal',
        drinks: true,
        regular: true,
        lunchTimeStart: '',
        lunchTimeEnd: '',
        sizes: [{ value: 'Family' }],
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Family Meal 1',
        category: 'Family Meals',
        quantity:
          '2 Zinger + 2 Junior Zinger + 5 Pieces Chicken + 1.5 Liter Drink',
        price: '1499',
        net: '0',
        count: '0',
        type: 'single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Family Meal 2',
        category: 'Family Meals',
        quantity:
          '8 Pices Chicken + 3 Junior Zinger + 1 Large Fries +1.5 Liter Drink',
        price: '1949',
        net: '0',
        count: '0',
        type: 'single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Lunch Deal 1',
        category: 'Lunch Deals',
        quantity: '1 Junior Zinger + 1 Reg Drink',
        price: '160',
        net: '0',
        count: '0',
        type: 'single',
        drinks: true,
        regular: false,
        lunchTimeStart: '12:00',
        lunchTimeEnd: '15:00',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Lunch Deal 2',
        category: 'Lunch Deals',
        quantity: '1 P.P Regular Pizza + 1 Reg Drink',
        price: '260',
        net: '0',
        count: '0',
        type: 'deal',
        drinks: true,
        regular: true,
        lunchTimeStart: '12:00',
        lunchTimeEnd: '15:00',
        sizes: [{ value: 'Personal Pan' }],
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Lunch Deal 3',
        category: 'Lunch Deals',
        quantity: '2 Chicken Pieces + 1 Reg Drink',
        price: '299',
        net: '0',
        count: '0',
        type: 'single',
        drinks: true,
        regular: false,
        lunchTimeStart: '12:00',
        lunchTimeEnd: '15:00',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Smoke n Flames Special Burger',
        category: 'Burgers',
        quantity: '',
        price: '299',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Lunch Deal 4',
        category: 'Lunch Deals',
        quantity: '1 Chicken Shawarma + 1 Reg Drink',
        price: '140',
        net: '0',
        count: '0',
        type: 'single',
        drinks: true,
        regular: false,
        lunchTimeStart: '12:00',
        lunchTimeEnd: '15:00',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Lunch Deal 5',
        category: 'Lunch Deals',
        quantity: '5 P.P Regular Pizza + 10 Hot Wings + 1.5 Liter Drink',
        price: '1599',
        net: '0',
        count: '0',
        type: 'deal',
        drinks: true,
        regular: true,
        lunchTimeStart: '12:00',
        lunchTimeEnd: '15:00',
        sizes: [
          { value: 'Personal Pan 1' },
          { value: 'Personal Pan 2' },
          { value: 'Personal Pan 3' },
          { value: 'Personal Pan 4' },
          { value: 'Personal Pan 5' },
        ],
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Malai Boti Crust',
        category: 'Stuffed Crust Pizza',
        quantity: 'Medium',
        price: '750',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: true,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Malai Boti Crust',
        category: 'Stuffed Crust Pizza',
        quantity: 'Large',
        price: '1080',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Malai Boti Crust',
        category: 'Stuffed Crust Pizza',
        quantity: 'Family',
        price: '1650',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Seekh Kabab Crust',
        category: 'Stuffed Crust Pizza',
        quantity: 'Small',
        price: '390',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Seekh Kabab Crust',
        category: 'Stuffed Crust Pizza',
        quantity: 'Medium',
        price: '750',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Seekh Kabab Crust',
        category: 'Stuffed Crust Pizza',
        quantity: 'Large',
        price: '1080',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Seekh Kabab Crust',
        category: 'Stuffed Crust Pizza',
        quantity: 'Family',
        price: '1650',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Lunch Deal 6',
        category: 'Lunch Deals',
        quantity: '3 P.P Regular Pizza + 6 Pcs Hot Wings + 1 Liter Drink',
        price: '999',
        net: '0',
        count: '0',
        type: 'deal',
        drinks: true,
        regular: true,
        lunchTimeStart: '12:00',
        lunchTimeEnd: '15:00',
        sizes: [
          { value: 'Personal Pan 1' },
          { value: 'Personal Pan 2' },
          { value: 'Personal Pan 3' },
        ],
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Mighty Zinger Burger',
        category: 'Burgers',
        quantity: '',
        price: '320',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Regular Drink',
        category: 'Beverages',
        quantity: '',
        price: '40',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: '500 ml Drink',
        category: 'Beverages',
        quantity: '',
        price: '60',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: '1 Litre Drink',
        category: 'Beverages',
        quantity: '',
        price: '90',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: '1.5 Litre Drink',
        category: 'Beverages',
        quantity: '',
        price: '120',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Mineral Water',
        category: 'Beverages',
        quantity: 'Small',
        price: '40',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Mineral Water',
        category: 'Beverages',
        quantity: 'Large',
        price: '80',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'French Fries',
        category: 'French Fries',
        quantity: 'Regular',
        price: '90',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'French Fries',
        category: 'French Fries',
        quantity: 'Large',
        price: '180',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'French Fries',
        category: 'French Fries',
        quantity: 'Family',
        price: '270',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Masala Fries',
        category: 'Masala Fries',
        quantity: 'Regular',
        price: '100',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Masala Fries',
        category: 'Masala Fries',
        quantity: 'Large',
        price: '200',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Masala Fries',
        category: 'Masala Fries',
        quantity: 'Family',
        price: '300',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Meal 1',
        category: 'Burger Meal',
        quantity: 'Junior Zinger + Drink',
        price: '170',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Meal 2',
        category: 'Burger Meal',
        quantity: 'Reggy Burger + Drink',
        price: '170',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Meal 3',
        category: 'Burger Meal',
        quantity: 'Zinger Burger + Drink',
        price: '270',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Meal 4',
        category: 'Burger Meal',
        quantity: 'Beef Burger + Fires + Drink',
        price: '299',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Meal 5',
        category: 'Burger Meal',
        quantity: 'Peri Peri Burger + Drink',
        price: '330',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Meal 6',
        category: 'Burger Meal',
        quantity: 'Chapli Burger + Fires + Drink',
        price: '260',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Meal 7',
        category: 'Burger Meal',
        quantity: 'Grilled Burger + Fires + Drink',
        price: '370',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Meal 8',
        category: 'Burger Meal',
        quantity: 'Smoke n Flames Special Burger + Drink',
        price: '330',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Meal 9',
        category: 'Burger Meal',
        quantity: 'Mighty Zinger Burger + Drink',
        price: '350',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Flame Cheese Lover',
        category: 'Regular Pizza',
        quantity: 'Small',
        price: '320',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Flame Cheese Lover',
        category: 'Regular Pizza',
        quantity: 'Medium',
        price: '650',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Flame Cheese Lover',
        category: 'Regular Pizza',
        quantity: 'Large',
        price: '900',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Flame Cheese Lover',
        category: 'Regular Pizza',
        quantity: 'Family',
        price: '1400',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Smoke n Flames Special Pizza',
        category: 'Special Pizza',
        quantity: 'Personal Pan',
        price: '270',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Smoke n Flames Special Pizza',
        category: 'Special Pizza',
        quantity: 'Small',
        price: '340',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Smoke n Flames Special Pizza',
        category: 'Special Pizza',
        quantity: 'Medium',
        price: '680',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Smoke n Flames Special Pizza',
        category: 'Special Pizza',
        quantity: 'Large',
        price: '950',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Smoke n Flames Special Pizza',
        category: 'Special Pizza',
        quantity: 'Family',
        price: '1500',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Chicken Chapli Kabab Pizza',
        category: 'Special Pizza',
        quantity: 'Personal Pan',
        price: '270',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Chicken Chapli Kabab Pizza',
        category: 'Special Pizza',
        quantity: 'Small',
        price: '340',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Chicken Chapli Kabab Pizza',
        category: 'Special Pizza',
        quantity: 'Medium',
        price: '680',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Chicken Chapli Kabab Pizza',
        category: 'Special Pizza',
        quantity: 'Large',
        price: '950',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Chicken Chapli Kabab Pizza',
        category: 'Special Pizza',
        quantity: 'Family',
        price: '1500',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Malai Boti Pizza',
        category: 'Special Pizza',
        quantity: 'Personal Pan',
        price: '270',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Malai Boti Pizza',
        category: 'Special Pizza',
        quantity: 'Small',
        price: '340',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Malai Boti Pizza',
        category: 'Special Pizza',
        quantity: 'Medium',
        price: '680',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Malai Boti Pizza',
        category: 'Special Pizza',
        quantity: 'Large',
        price: '950',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Malai Boti Pizza',
        category: 'Special Pizza',
        quantity: 'Family',
        price: '1500',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Mughalai Pizza',
        category: 'Special Pizza',
        quantity: 'Personal Pan',
        price: '270',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Mughalai Pizza',
        category: 'Special Pizza',
        quantity: 'Small',
        price: '340',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Mughalai Pizza',
        category: 'Special Pizza',
        quantity: 'Medium',
        price: '680',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Mughalai Pizza',
        category: 'Special Pizza',
        quantity: 'Large',
        price: '950',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Mughalai Pizza',
        category: 'Special Pizza',
        quantity: 'Family',
        price: '1500',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Super Supreme Pizza',
        category: 'Special Pizza',
        quantity: 'Personal Pan',
        price: '270',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Super Supreme Pizza',
        category: 'Special Pizza',
        quantity: 'Small',
        price: '340',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Super Supreme Pizza',
        category: 'Special Pizza',
        quantity: 'Medium',
        price: '680',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Super Supreme Pizza',
        category: 'Special Pizza',
        quantity: 'Large',
        price: '950',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Super Supreme Pizza',
        category: 'Special Pizza',
        quantity: 'Family',
        price: '1500',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Afghani Pizza',
        category: 'Special Pizza',
        quantity: 'Personal Pan',
        price: '270',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Afghani Pizza',
        category: 'Special Pizza',
        quantity: 'Small',
        price: '340',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Afghani Pizza',
        category: 'Special Pizza',
        quantity: 'Medium',
        price: '680',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Afghani Pizza',
        category: 'Special Pizza',
        quantity: 'Large',
        price: '950',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Afghani Pizza',
        category: 'Special Pizza',
        quantity: 'Family',
        price: '1500',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Behari Seekh Kabab Pizza',
        category: 'Special Pizza',
        quantity: 'Personal Pan',
        price: '270',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Behari Seekh Kabab Pizza',
        category: 'Special Pizza',
        quantity: 'Small',
        price: '340',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Behari Seekh Kabab Pizza',
        category: 'Special Pizza',
        quantity: 'Medium',
        price: '680',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Behari Seekh Kabab Pizza',
        category: 'Special Pizza',
        quantity: 'Large',
        price: '950',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Behari Seekh Kabab Pizza',
        category: 'Special Pizza',
        quantity: 'Family',
        price: '1500',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Turkish Pizza',
        category: 'Turkish Pizza',
        quantity: 'Medium',
        price: '750',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Turkish Pizza',
        category: 'Turkish Pizza',
        quantity: 'Large',
        price: '1080',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Turkish Pizza',
        category: 'Turkish Pizza',
        quantity: 'Family',
        price: '1650',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Flames Combo 5',
        category: 'Flames Combo',
        quantity: '1 Quarter Peri Peri Chicken + 1 Reg Fries + 1 Reg Drink',
        price: '320',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Flames Combo 6',
        category: 'Flames Combo',
        quantity: '2 Junior Zinger Burger + 1 Pc Chicken + 500 ml Drink',
        price: '470',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Flames Combo 7',
        category: 'Flames Combo',
        quantity: '3 Junior Zinger Burger + 1 Liter Drink',
        price: '490',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Flames Combo 8',
        category: 'Flames Combo',
        quantity: '1 Zinger Burger + 3 Pcs Hot Wings + 1 Reg Drink',
        price: '360',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Flames Combo 9',
        category: 'Flames Combo',
        quantity: '1 Zinger Burger + 1 Grilled Paratha + 500 ml Drink',
        price: '440',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Flames Combo 10',
        category: 'Flames Combo',
        quantity: '1 Medium Regular Pizza + 2 Pieces Chicken + 2 Reg Drink',
        price: '999',
        net: '0',
        count: '0',
        type: 'deal',
        drinks: true,
        regular: true,
        lunchTimeStart: '',
        lunchTimeEnd: '',
        sizes: [{ value: 'Medium' }],
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Deal 5',
        category: 'Deals',
        quantity: 'Maxican Chicken Sandwich + Fries + Reg Drink',
        price: '460',
        net: '0',
        count: '0',
        type: 'single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Personal Pan Pizza Deal',
        category: 'Mid Night Deal',
        quantity: 'Buy 1 Get 1 Free',
        price: '449',
        net: '0',
        count: '0',
        type: 'deal',
        drinks: true,
        regular: true,
        lunchTimeStart: '',
        lunchTimeEnd: '',
        sizes: [{ value: 'Personal Pan 1' }, { value: 'Personal Pan 2' }],
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Medium Pizza Deal',
        category: 'Mid Night Deal',
        quantity: 'Buy 1 Get 1 Free',
        price: '1099',
        net: '0',
        count: '0',
        type: 'deal',
        drinks: true,
        regular: true,
        lunchTimeStart: '',
        lunchTimeEnd: '',
        sizes: [{ value: 'Medium 1' }, { value: 'Medium 2' }],
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Large Pizza Deal',
        category: 'Mid Night Deal',
        quantity: 'Buy 1 Get 1 Free',
        price: '1599',
        net: '0',
        count: '0',
        type: 'deal',
        drinks: true,
        regular: true,
        lunchTimeStart: '',
        lunchTimeEnd: '',
        sizes: [{ value: 'Large 1' }, { value: 'Large 2' }],
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Fried Chicken',
        category: 'Chicken Piece',
        quantity: '1 Piece',
        price: '150',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Fried Chicken',
        category: 'Chicken Piece',
        quantity: '5 Pieces',
        price: '700',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Fried Chicken',
        category: 'Chicken Piece',
        quantity: '10 Pieces',
        price: '1300',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Hot Wings',
        category: 'Hot Wings',
        quantity: '5 Pieces',
        price: '170',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Hot Wings',
        category: 'Hot Wings',
        quantity: '10 Pieces',
        price: '330',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Peri Peri  Hot Wings',
        category: 'Hot Wings',
        quantity: '5 Pieces',
        price: '190',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Peri Peri  Hot Wings',
        category: 'Hot Wings',
        quantity: '10 Pieces',
        price: '350',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Chicken Nuggets',
        category: 'Nuggets',
        quantity: '5 Pieces',
        price: '130',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Chicken Nuggets',
        category: 'Nuggets',
        quantity: '10 Pieces',
        price: '230',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Peri Peri   + Fries (Extra Hot)',
        category: 'Peri Peri Chicken',
        quantity: 'Quarter',
        price: '299',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Peri Peri  Chicken + Fries ( Hot)',
        category: 'Peri Peri Chicken',
        quantity: 'Quarter',
        price: '299',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Peri Peri  Chicken + Fries (Mild)',
        category: 'Peri Peri Chicken',
        quantity: 'Quarter',
        price: '299',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Peri Peri Chicken + Fries (Lemon & Herb)',
        category: 'Peri Peri Chicken',
        quantity: 'Quarter',
        price: '299',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Peri Peri  Chicken + Fries (Extra Hot)',
        category: 'Peri Peri Chicken',
        quantity: 'Half',
        price: '599',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Peri Peri  Chicken + Fries ( Hot)',
        category: 'Peri Peri Chicken',
        quantity: 'Half',
        price: '599',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Peri Peri  Chicken + Fries (Mild)',
        category: 'Peri Peri Chicken',
        quantity: 'Half',
        price: '599',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Peri Peri  Chicken + Fries (Lemon & Herb)',
        category: 'Peri Peri Chicken',
        quantity: 'Half',
        price: '599',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Peri Peri  Chicken + Fries (Extra Hot)',
        category: 'Peri Peri Chicken',
        quantity: 'Full',
        price: '1199',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Peri Peri  Chicken + Fries ( Hot)',
        category: 'Peri Peri Chicken',
        quantity: 'Full',
        price: '1199',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Peri Peri  Chicken + Fries (Mild)',
        category: 'Peri Peri Chicken',
        quantity: 'Full',
        price: '1199',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f3fae7daf3a6d3ac9089727',
        productName: 'Peri Peri  Chicken + Fries (Lemon & Herb)',
        category: 'Peri Peri Chicken',
        quantity: 'Full',
        price: '1199',
        net: '0',
        count: '0',
        type: 'Single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
    ]);

    return res.json({
      status: '200',
      msg: 'Product added successfully',
    });
  } catch (err) {
    return res.json({
      status: '404',
      error: err.toString(),
      msg: `Looks like something went wrong on our side. Sorry for the inconvenience.`,
    });
  }
}); */

router.get('/addAvailability', async (req, res) => {
  try {
    await Products.updateMany({}, { available: 'in stock' });

    return res.json({
      status: '200',
      msg: 'Products updated',
    });
  } catch (err) {
    return res.json({
      status: '404',
      error: err.toString(),
      msg: `Looks like something went wrong on our side. Sorry for the inconvenience.`,
    });
  }
});

module.exports = router;
