const express = require('express');
const _ = require('lodash');

const router = express.Router();

const Users = require('../../models/userModel');
const Products = require('../../models/productsModel');
const Flavours = require('../../models/flavoursAndDrinks');
const Marts = require('../../models/martsModel');
const Offers = require('../../models/offersModel');

const notify = require('../../notificationHandler/handler');

router.post('/allProducts', async (req, res) => {
  try {
    const { martId } = req.body;
    let finalData = [];

    const allCategories = await Products.distinct('category', { martId });

    const { shopType } = await Marts.findById(martId);

    if (shopType === 'restaurant') {
      await Promise.all(
        allCategories.map(async ac => {
          const query = {
            category: ac,
            martId,
            available: 'in stock',
          };

          const products = await Products.find(query).sort({ productName: 1 });

          await Promise.all(
            products.map(async p => {
              if (
                p.type === 'deal' &&
                (p.regular === undefined ||
                  p.regular === null ||
                  p.regular === false)
              ) {
                const { flavours } = await Flavours.findOne({ martId });
                p.flavours = flavours;
              }

              if (p.type === 'deal' && p.regular === true) {
                const { regularFlavours } = await Flavours.findOne({ martId });
                p.flavours = regularFlavours;
              }

              if (p.drinks === true) {
                const { drinks } = await Flavours.findOne({ martId });
                p.allDrinks = drinks;
              }
            })
          );

          const data = {
            category: ac,
            data: products,
          };

          await Promise.resolve(data);
          finalData.push(data);
        })
      );

      finalData = _.orderBy(finalData, ['category'], ['desc']);

      return res.json({
        status: '200',
        data: finalData,
      });
    }

    await Promise.all(
      allCategories.map(async ac => {
        const query = {
          category: ac,
          martId,
          available: 'in stock',
        };

        const martProducts = await Products.find(query).sort({
          productName: 1,
        });

        const data = {
          category: ac,
          data: martProducts,
        };

        await Promise.resolve(data);
        finalData.push(data);
      })
    );

    finalData = _.orderBy(finalData, ['category'], ['desc']);

    return res.json({
      status: '200',
      data: finalData,
    });
  } catch (err) {
    return res.json({
      status: '404',
      msg: `Looks like something went wrong on our side. Sorry for the inconvenience.`,
    });
  }
});

router.post('/allRestaurantProducts', async (req, res) => {
  try {
    const { martId } = req.body;
    const allCategories = [];
    let finalData = [];

    const categories = await Products.find({ martId })
      .sort({
        category: 1,
      })
      .select('category');

    await Promise.all(
      categories.map(c => {
        if (!allCategories.includes(c.category)) {
          allCategories.push(c.category);
        }
        return allCategories;
      })
    );

    await Promise.all(
      allCategories.map(async ac => {
        const query = {
          category: ac,
          martId,
        };

        const products = await Products.find(query).sort({ productName: 1 });

        const data = {
          category: ac,
          data: products,
        };

        await Promise.resolve(data);
        await Promise.resolve(finalData.push(data));
      })
    );

    finalData = _.orderBy(finalData, ['category'], ['desc']);

    return res.json({
      status: '200',
      data: finalData,
    });
  } catch (err) {
    return res.json({
      status: '404',
      msg: `Looks like something went wrong on our side. Sorry for the inconvenience.`,
    });
  }
});

router.post('/allCategories', async (req, res) => {
  try {
    const { martId } = req.body;
    const allCategories = [];

    const categories = await Products.find({ martId })
      .sort({
        category: 1,
      })
      .select('category');

    await Promise.all(
      categories.map(c => {
        if (!allCategories.includes(c.category)) {
          allCategories.push(c.category);
        }
        return allCategories;
      })
    );

    return res.json({
      status: '200',
      data: allCategories,
    });
  } catch (err) {
    return res.json({
      status: '404',
      msg: `Looks like something went wrong on our side. Sorry for the inconvenience.`,
    });
  }
});

router.post('/productAvailability', async (req, res) => {
  try {
    const { productId } = req.body;

    await Products.findByIdAndUpdate(productId, { $set: req.body });

    return res.json({
      status: '200',
      msg: 'Product status updated',
    });
  } catch (err) {
    return res.json({
      status: '404',
      error: err.toString(),
      msg: `Looks like something went wrong on our side. Sorry for the inconvenience.`,
    });
  }
});

router.post('/allMartProducts', async (req, res) => {
  try {
    const { martId, type } = req.body;
    let products;

    if (type === 'admin') {
      products = await Products.find({ martId }).sort({ productName: 1 });
    } else {
      products = await Products.find({ martId, available: 'in stock' }).sort({
        productName: 1,
      });
    }

    return res.json({
      status: '200',
      data: products,
    });
  } catch (err) {
    return res.json({
      status: '404',
      error: err.toString(),
      msg: `Looks like something went wrong on our side. Sorry for the inconvenience.`,
    });
  }
});

router.get('/addAvailability', async (req, res) => {
  try {
    await Products.updateMany({}, { available: 'in stock' });

    return res.json({
      status: '200',
      msg: 'Products updated',
    });
  } catch (err) {
    return res.json({
      status: '404',
      error: err.toString(),
      msg: `Looks like something went wrong on our side. Sorry for the inconvenience.`,
    });
  }
});

router.post('/updateProductsAvailability', async (req, res) => {
  try {
    const { category, martId, available } = req.body;

    const query = {
      category,
      martId,
    };

    await Products.updateMany(query, { $set: req.body });

    res.json({
      status: '200',
      msg: 'Status successfully updated',
    });

    if (available === 'in stock') {
      const { offers } = await Offers.findOne({ martId });

      offers.forEach(async offer => {
        if (offer.name === category) {
          const users = await Users.find({ type: 'user' });

          users.forEach(async user => {
            await notify.user(offer.text, user.playerId, { flag: 'offer' });
          });
        }
      });
    }
  } catch (err) {
    return res.json({
      status: '404',
      error: err.toString(),
      msg: `Looks like something went wrong on our side. Sorry for the inconvenience.`,
    });
  }
});

/* router.get('/addBulkProducts/', async (req, res) => {
  try {
    await Products.insertMany([
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Meal 1',
        category: 'Mazaydar Deals',
        quantity: '1 Krizma Burger + 1 Reg Fries + 1 Reg Drink',
        price: '370',
        net: '0',
        count: '0',
        type: 'single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'F.C Special Pizza',
        category: 'Special Pizza',
        quantity: 'Small',
        price: '299',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'F.C Special Pizza',
        category: 'Special Pizza',
        quantity: 'Medium',
        price: '699',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'F.C Special Pizza',
        category: 'Special Pizza',
        quantity: 'Large',
        price: '999',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'F.C Special Pizza',
        category: 'Special Pizza',
        quantity: 'Family',
        price: '1549',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Tikka Pizza',
        category: 'Regular Pizza',
        quantity: 'Small',
        price: '270',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Tikka Pizza',
        category: 'Regular Pizza',
        quantity: 'Medium',
        price: '650',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Tikka Pizza',
        category: 'Regular Pizza',
        quantity: 'Large',
        price: '950',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Tikka Pizza',
        category: 'Regular Pizza',
        quantity: 'Family',
        price: '1400',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Kababish Pizza',
        category: 'Special Pizza',
        quantity: 'Small',
        price: '299',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Kababish Pizza',
        category: 'Special Pizza',
        quantity: 'Medium',
        price: '699',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Kababish Pizza',
        category: 'Special Pizza',
        quantity: 'Large',
        price: '999',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Kababish Pizza',
        category: 'Special Pizza',
        quantity: 'Family',
        price: '1549',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Fajita Pizza',
        category: 'Regular Pizza',
        quantity: 'Small',
        price: '270',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Fajita Pizza',
        category: 'Regular Pizza',
        quantity: 'Medium',
        price: '650',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Fajita Pizza',
        category: 'Regular Pizza',
        quantity: 'Large',
        price: '950',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Fajita Pizza',
        category: 'Regular Pizza',
        quantity: 'Family',
        price: '1400',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Euro Pizza',
        category: 'Special Pizza',
        quantity: 'Small',
        price: '299',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Euro Pizza',
        category: 'Special Pizza',
        quantity: 'Medium',
        price: '699',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Euro Pizza',
        category: 'Special Pizza',
        quantity: 'Large',
        price: '999',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Euro Pizza',
        category: 'Special Pizza',
        quantity: 'Family',
        price: '1549',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Pickle Pizza',
        category: 'Regular Pizza',
        quantity: 'Small',
        price: '270',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Pickle Pizza',
        category: 'Regular Pizza',
        quantity: 'Medium',
        price: '650',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Pickle Pizza',
        category: 'Regular Pizza',
        quantity: 'Large',
        price: '950',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Pickle Pizza',
        category: 'Regular Pizza',
        quantity: 'Family',
        price: '1400',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Afghani Tikka Pizza',
        category: 'Special Pizza',
        quantity: 'Small',
        price: '299',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Afghani Tikka Pizza',
        category: 'Special Pizza',
        quantity: 'Medium',
        price: '699',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Afghani Tikka Pizza',
        category: 'Special Pizza',
        quantity: 'Large',
        price: '999',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Afghani Tikka Pizza',
        category: 'Special Pizza',
        quantity: 'Family',
        price: '1549',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Vegetarian Pizza',
        category: 'Regular Pizza',
        quantity: 'Small',
        price: '270',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Vegetarian Pizza',
        category: 'Regular Pizza',
        quantity: 'Medium',
        price: '650',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Vegetarian Pizza',
        category: 'Regular Pizza',
        quantity: 'Large',
        price: '950',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Vegetarian Pizza',
        category: 'Regular Pizza',
        quantity: 'Family',
        price: '1400',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Super Supreme Pizza',
        category: 'Special Pizza',
        quantity: 'Small',
        price: '299',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Super Supreme Pizza',
        category: 'Special Pizza',
        quantity: 'Medium',
        price: '699',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Super Supreme Pizza',
        category: 'Special Pizza',
        quantity: 'Large',
        price: '999',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Super Supreme Pizza',
        category: 'Special Pizza',
        quantity: 'Family',
        price: '1549',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Sausage Pizza',
        category: 'Regular Pizza',
        quantity: 'Small',
        price: '270',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Sausage Pizza',
        category: 'Regular Pizza',
        quantity: 'Medium',
        price: '650',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Sausage Pizza',
        category: 'Regular Pizza',
        quantity: 'Large',
        price: '950',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Sausage Pizza',
        category: 'Regular Pizza',
        quantity: 'Family',
        price: '1400',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Chicken Chapli Kabab',
        category: 'Burgers',
        quantity: '',
        price: '150',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Burger Meal 1',
        category: 'Burgers Meal',
        quantity: 'Chicken Chapli Kabab + Fries + Drink',
        price: '250',
        net: '0',
        count: '0',
        type: 'single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Chicken BBQ Burger',
        category: 'Burgers',
        quantity: '',
        price: '175',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Burger Meal 2',
        category: 'Burgers Meal',
        quantity: 'Chicken BBQ Burger + Fries + Drink',
        price: '270',
        net: '0',
        count: '0',
        type: 'single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Chicken Krizma Burger',
        category: 'Burgers',
        quantity: '',
        price: '250',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Burger Meal 3',
        category: 'Burgers Meal',
        quantity: 'Chicken Krizma Burger + Drink',
        price: '290',
        net: '0',
        count: '0',
        type: 'single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Chicken Reggy Burger',
        category: 'Burgers',
        quantity: '',
        price: '140',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Burger Meal 4',
        category: 'Burgers Meal',
        quantity: 'Chicken Reggy Burger + Drink',
        price: '180',
        net: '0',
        count: '0',
        type: 'single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Chicken Junior Zinger',
        category: 'Burgers',
        quantity: '',
        price: '140',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Burger Meal 5',
        category: 'Burgers Meal',
        quantity: 'Chicken Junior Zinger + Drink',
        price: '180',
        net: '0',
        count: '0',
        type: 'single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Chicken Double Dozer',
        category: 'Burgers',
        quantity: '',
        price: '380',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Burger Meal 6',
        category: 'Burgers Meal',
        quantity: 'Chicken Double Dozer + Drink',
        price: '400',
        net: '0',
        count: '0',
        type: 'single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Chicken Double Mazza',
        category: 'Burgers',
        quantity: '',
        price: '230',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Burger Meal 7',
        category: 'Burgers Meal',
        quantity: 'Chicken Double Mazza + Fries + Drink',
        price: '330',
        net: '0',
        count: '0',
        type: 'single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'FC Special Shawarma',
        category: 'Shawarma',
        quantity: '',
        price: '150',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Chicken Shawarma',
        category: 'Shawarma',
        quantity: '',
        price: '110',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Chic Cheese Shawarma',
        category: 'Shawarma',
        quantity: '',
        price: '140',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Zinger Shawarma',
        category: 'Shawarma',
        quantity: '',
        price: '130',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Achari Shawarma',
        category: 'Shawarma',
        quantity: '',
        price: '120',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'FC Special Paratha Roll',
        category: 'Paratha Roll',
        quantity: '',
        price: '150',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Chicken Paratha Roll',
        category: 'Paratha Roll',
        quantity: '',
        price: '110',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Chic-Cheese Paratha Roll',
        category: 'Paratha Roll',
        quantity: '',
        price: '140',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Small Pizza Deal',
        category: 'Mid Night Offer',
        quantity: '1  Small Pizza + 1 Small Free',
        price: '499',
        net: '0',
        count: '0',
        type: 'deal',
        drinks: false,
        regular: false,
        lunchTimeStart: '21:00',
        lunchTimeEnd: '23:30',
        sizes: [
          {
            value: 'Small 1',
          },
          {
            value: 'Small 2',
          },
        ],
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Medium Pizza Deal',
        category: 'Mid Night Offer',
        quantity: '1 Medium Pizza + 1 Medium Free',
        price: '999',
        net: '0',
        count: '0',
        type: 'deal',
        drinks: false,
        regular: false,
        lunchTimeStart: '21:00',
        lunchTimeEnd: '23:30',
        sizes: [
          {
            value: 'Medium 1',
          },
          {
            value: 'Medium 2',
          },
        ],
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Large Pizza Deal',
        category: 'Mid Night Offer',
        quantity: '1 Large Pizza + 1 Large Free',
        price: '1399',
        net: '0',
        count: '0',
        type: 'deal',
        drinks: false,
        regular: false,
        lunchTimeStart: '21:00',
        lunchTimeEnd: '23:30',
        sizes: [
          {
            value: 'Large 1',
          },
          {
            value: 'large 2',
          },
        ],
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Meal 2',
        category: 'Mazaydar Deals',
        quantity: '1 Reggy Burger + 1 Reg Fries + 1 Reg Drink',
        price: '270',
        net: '0',
        count: '0',
        type: 'single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Meal 3',
        category: 'Mazaydar Deals',
        quantity: '3 Pcs Chicken + 1 Reg Drink',
        price: '399',
        net: '0',
        count: '0',
        type: 'single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Meal 4',
        category: 'Mazaydar Deals',
        quantity: '2 Pcs Chicken + 1 Rice + 1 Reg Drink',
        price: '440',
        net: '0',
        count: '0',
        type: 'single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Combo 1',
        category: 'Combo Special',
        quantity: '1 Krizma Burger + 1 Reg Fries + 1 Reg Drink + 1 Pc Chicken',
        price: '480',
        net: '0',
        count: '0',
        type: 'single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Combo 2',
        category: 'Combo Special',
        quantity: '1 Reggy Burger + 1 Reg Fries + 1 Reg Drink + 1 Pc Chicken',
        price: '390',
        net: '0',
        count: '0',
        type: 'single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Combo 3',
        category: 'Combo Special',
        quantity: '3 Pcs Chicken + 1 Reg Drink + 1 Reg Fries + 1 Dinner Roll',
        price: '540',
        net: '0',
        count: '0',
        type: 'single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Combo 4',
        category: 'Combo Special',
        quantity:
          '4 Pcs Chicken + 2 Reg Drink + 1 Reg Fries + 2 Dinner Roll + 1 Rice',
        price: '850',
        net: '0',
        count: '0',
        type: 'single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Super Family Meal',
        category: 'Combo Special',
        quantity:
          '8 Pcs Chicken + 3 Krizma + 1 Reggy Burger + 8 Reg Drink + 1 Family Fries',
        price: '1999',
        net: '0',
        count: '0',
        type: 'single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Fried Fish Deal',
        category: 'Combo Special',
        quantity: '3 Pcs Fried Fish + 1 Reg Drink',
        price: '399',
        net: '0',
        count: '0',
        type: 'single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Hot Wings Deal',
        category: 'Combo Special',
        quantity: '10 Hot Wings + 1 Reg Drink',
        price: '350',
        net: '0',
        count: '0',
        type: 'single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Fried Fish Burger',
        category: 'Burgers',
        quantity: '',
        price: '280',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Burger Meal 8',
        category: 'Burgers Meal',
        quantity: 'Fried Fish Burger + Fries + Drink',
        price: '380',
        net: '0',
        count: '0',
        type: 'single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Oven Baked Wings Deal',
        category: 'Combo Special',
        quantity: '10 Oven Bake Wings + 1 Reg Drink',
        price: '350',
        net: '0',
        count: '0',
        type: 'single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Kids Meal',
        category: 'Combo Special',
        quantity: '5 Pcs Nuggets + 1 Dinner Roll + 1 Reg Fries + 1 Reg Drink',
        price: '300',
        net: '0',
        count: '0',
        type: 'single',
        drinks: true,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Chapli Kabab Pizza',
        category: 'Special Pizza',
        quantity: 'Small',
        price: '299',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Chapli Kabab Pizza',
        category: 'Special Pizza',
        quantity: 'Medium',
        price: '699',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Chapli Kabab Pizza',
        category: 'Special Pizza',
        quantity: 'Large',
        price: '999',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Chapli Kabab Pizza',
        category: 'Special Pizza',
        quantity: 'Family',
        price: '1549',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Cheese Pizza',
        category: 'Regular Pizza',
        quantity: 'Small',
        price: '270',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Cheese Pizza',
        category: 'Regular Pizza',
        quantity: 'Medium',
        price: '650',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Cheese Pizza',
        category: 'Regular Pizza',
        quantity: 'Large',
        price: '950',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Cheese Pizza',
        category: 'Regular Pizza',
        quantity: 'Family',
        price: '1400',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Mughliyai Pizza',
        category: 'Special Pizza',
        quantity: 'Small',
        price: '299',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Mughliyai Pizza',
        category: 'Special Pizza',
        quantity: 'Medium',
        price: '699',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Mughliyai Pizza',
        category: 'Special Pizza',
        quantity: 'Large',
        price: '999',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Mughliyai Pizza',
        category: 'Special Pizza',
        quantity: 'Family',
        price: '1549',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Pepperoni Pizza',
        category: 'Regular Pizza',
        quantity: 'Small',
        price: '270',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Pepperoni Pizza',
        category: 'Regular Pizza',
        quantity: 'Medium',
        price: '650',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Pepperoni Pizza',
        category: 'Regular Pizza',
        quantity: 'Large',
        price: '950',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Pepperoni Pizza',
        category: 'Regular Pizza',
        quantity: 'Family',
        price: '1400',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Deal 1',
        category: 'Exclusive Discounted Deals',
        quantity: '1 Small Regular Pizza + 1 Reg Drink',
        price: '299',
        net: '0',
        count: '0',
        type: 'deal',
        drinks: true,
        regular: true,
        lunchTimeStart: '',
        lunchTimeEnd: '',
        sizes: [
          {
            value: 'Small',
          },
        ],
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Deal 2',
        category: 'Exclusive Discounted Deals',
        quantity: '1 Medium Regular Pizza + 1 Ltr Drink',
        price: '699',
        net: '0',
        count: '0',
        type: 'deal',
        drinks: true,
        regular: true,
        lunchTimeStart: '',
        lunchTimeEnd: '',
        sizes: [
          {
            value: 'Medium',
          },
        ],
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Deal 3',
        category: 'Exclusive Discounted Deals',
        quantity: '1 Large Regular Pizza + 1.5 Ltr Drink',
        price: '999',
        net: '0',
        count: '0',
        type: 'deal',
        drinks: true,
        regular: true,
        lunchTimeStart: '',
        lunchTimeEnd: '',
        sizes: [
          {
            value: 'Large',
          },
        ],
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Deal 4',
        category: 'Exclusive Discounted Deals',
        quantity: '1 Family Regular Pizza + 2.2.5 Ltr Drink',
        price: '1499',
        net: '0',
        count: '0',
        type: 'deal',
        drinks: true,
        regular: true,
        lunchTimeStart: '',
        lunchTimeEnd: '',
        sizes: [
          {
            value: 'Family',
          },
        ],
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Arabian Paratha Roll',
        category: 'Paratha Roll',
        quantity: '',
        price: '150',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Achari Paratha Roll',
        category: 'Paratha Roll',
        quantity: '',
        price: '120',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Zinger Paratha Roll',
        category: 'Paratha Roll',
        quantity: '',
        price: '130',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Hot Wings',
        category: 'Side Order',
        quantity: '10 Pieces',
        price: '330',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Hot Wings',
        category: 'Side Order',
        quantity: '5 Pieces',
        price: '180',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Chicken Piece',
        category: 'Side Order',
        quantity: '1 Piece',
        price: '140',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Chicken Piece',
        category: 'Side Order',
        quantity: '5 Pieces',
        price: '640',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Oven Baked Wings',
        category: 'Side Order',
        quantity: '5 Pieces',
        price: '180',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Oven Baked Wings',
        category: 'Side Order',
        quantity: '10 Pieces',
        price: '330',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'French Fries',
        category: 'Side Order',
        quantity: 'Regular',
        price: '90',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'French Fries',
        category: 'Side Order',
        quantity: 'Large',
        price: '150',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'French Fries',
        category: 'Side Order',
        quantity: 'Family',
        price: '270',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Nuggets',
        category: 'Side Order',
        quantity: '10 Pieces',
        price: '230',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Nuggets',
        category: 'Side Order',
        quantity: '5 Pieces',
        price: '120',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Hot Shots',
        category: 'Side Order',
        quantity: '10 Pieces',
        price: '140',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Rice',
        category: 'Side Order',
        quantity: '',
        price: '120',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Cheese Slice',
        category: 'Side Order',
        quantity: '',
        price: '30',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Dinner Roll',
        category: 'Side Order',
        quantity: '',
        price: '30',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Mineral Water',
        category: 'Beverages',
        quantity: 'Small',
        price: '30',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Mineral Water',
        category: 'Beverages',
        quantity: 'Large',
        price: '70',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Regular Drink',
        category: 'Beverages',
        quantity: '300ml',
        price: '40',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Half Litre Drink',
        category: 'Beverages',
        quantity: '500ml',
        price: '60',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Tin Pack',
        category: 'Beverages',
        quantity: '',
        price: '60',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: '1 Litre Drink',
        category: 'Beverages',
        quantity: '',
        price: '100',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: '1.5 Litre Drink',
        category: 'Beverages',
        quantity: '',
        price: '120',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: '2.25 Litre Drink',
        category: 'Beverages',
        quantity: '',
        price: '180',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Pizza Extra Topping',
        category: "Add ON's",
        quantity: 'Small',
        price: '80',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Pizza Extra Topping',
        category: "Add ON's",
        quantity: 'Medium',
        price: '120',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Pizza Extra Topping',
        category: "Add ON's",
        quantity: 'Large',
        price: '220',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Pizza Extra Topping',
        category: "Add ON's",
        quantity: 'Family',
        price: '420',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Choclate Ice Cream Shake',
        category: 'Ice Cream Shakes',
        quantity: '',
        price: '150',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Very Vanilla Ice Cream Shake',
        category: 'Ice Cream Shakes',
        quantity: '',
        price: '150',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Oreo Ice Cream Shake',
        category: 'Ice Cream Shakes',
        quantity: '',
        price: '150',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'BlueBerry Ice Cream Shake',
        category: 'Ice Cream Shakes',
        quantity: '',
        price: '150',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Strawberry Ice Cream Shake',
        category: 'Ice Cream Shakes',
        quantity: '',
        price: '150',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Cookies & Cream Ice Cream Shake',
        category: 'Ice Cream Shakes',
        quantity: '',
        price: '150',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Coocunt Ice Cream Shake',
        category: 'Ice Cream Shakes',
        quantity: '',
        price: '150',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Vanilla Mint  Ice Cream Shake',
        category: 'Ice Cream Shakes',
        quantity: '',
        price: '150',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Kulfa Ice Cream Shake',
        category: 'Ice Cream Shakes',
        quantity: '',
        price: '150',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'White Berry Ice Cream Shake',
        category: 'Ice Cream Shakes',
        quantity: '',
        price: '150',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Chocolate Fudge Ice Cream Shake',
        category: 'Ice Cream Shakes',
        quantity: '',
        price: '200',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Nutella Ice Cream Shake',
        category: 'Ice Cream Shakes',
        quantity: '',
        price: '200',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'KitKat Ice Cream Shake',
        category: 'Ice Cream Shakes',
        quantity: '',
        price: '200',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Black Berry Smoothie',
        category: 'Smoothies',
        quantity: '',
        price: '200',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Blue Berry Smoothie',
        category: 'Smoothies',
        quantity: '',
        price: '200',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Banana Smoothie',
        category: 'Smoothies',
        quantity: '',
        price: '200',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Vild Berry Smoothie',
        category: 'Smoothies',
        quantity: '',
        price: '200',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Vanilla Smoothie',
        category: 'Smoothies',
        quantity: '',
        price: '200',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Mango Smoothie',
        category: 'Smoothies',
        quantity: '',
        price: '200',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Chocolate Smoothie',
        category: 'Smoothies',
        quantity: '',
        price: '200',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Caramel Smoothie',
        category: 'Smoothies',
        quantity: '',
        price: '200',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Kulfa Smoothie',
        category: 'Smoothies',
        quantity: '',
        price: '200',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Strawberry Smoothie',
        category: 'Smoothies',
        quantity: '',
        price: '200',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Tutti Fruti Smoothie',
        category: 'Smoothies',
        quantity: '',
        price: '200',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Peach Shake',
        category: 'Fresh Shakes',
        quantity: '',
        price: '120',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Strawberry Shake',
        category: 'Fresh Shakes',
        quantity: '',
        price: '120',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Banana Shake',
        category: 'Fresh Shakes',
        quantity: '',
        price: '110',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Pineapple Shake',
        category: 'Fresh Shakes',
        quantity: '',
        price: '150',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Apple Shake',
        category: 'Fresh Shakes',
        quantity: '',
        price: '110',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Mango Shake',
        category: 'Fresh Shakes',
        quantity: '',
        price: '120',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Falsa Juice',
        category: 'Fresh Juices',
        quantity: '',
        price: '130',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Mango Juice',
        category: 'Fresh Juices',
        quantity: '',
        price: '130',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Strawberry Juice',
        category: 'Fresh Juices',
        quantity: '',
        price: '130',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Pineapple Juice',
        category: 'Fresh Juices',
        quantity: '',
        price: '150',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Peach Juice',
        category: 'Fresh Juices',
        quantity: '',
        price: '130',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Apple Juice',
        category: 'Fresh Juices',
        quantity: '',
        price: '150',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Apple Ginger Juice',
        category: 'Fresh Juices',
        quantity: '',
        price: '130',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Orange Juice',
        category: 'Fresh Juices',
        quantity: '',
        price: '130',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Guava Juce',
        category: 'Fresh Juices',
        quantity: '',
        price: '130',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Frappuccino',
        category: 'Signature Cold',
        quantity: '',
        price: '200',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Cold Coffee',
        category: 'Signature Cold',
        quantity: '',
        price: '200',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Cold Coffee with Ice Cream',
        category: 'Signature Cold',
        quantity: '',
        price: '200',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Vanilla Cold Coffee',
        category: 'Signature Cold',
        quantity: '',
        price: '200',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Kulfa Cold Coffee',
        category: 'Signature Cold',
        quantity: '',
        price: '200',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Mango Cold Coffee',
        category: 'Signature Cold',
        quantity: '',
        price: '200',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Chocolate Cold Coffee',
        category: 'Signature Cold',
        quantity: '',
        price: '200',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Caramel Cold Coffee',
        category: 'Signature Cold',
        quantity: '',
        price: '200',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Strawberry Cold Coffee',
        category: 'Signature Cold',
        quantity: '',
        price: '200',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Tutti Fruti Cold Coffee',
        category: 'Signature Cold',
        quantity: '',
        price: '200',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Black Coffee',
        category: 'Hot Coffee',
        quantity: '',
        price: '120',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Latte Coffee',
        category: 'Hot Coffee',
        quantity: '',
        price: '150',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Cappuccino Coffee',
        category: 'Hot Coffee',
        quantity: '',
        price: '150',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Espresso Coffee',
        category: 'Hot Coffee',
        quantity: '',
        price: '130',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Americano Coffee',
        category: 'Hot Coffee',
        quantity: '',
        price: '130',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Hot Chocolate Coffee',
        category: 'Hot Coffee',
        quantity: '',
        price: '200',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Back Tea',
        category: 'Hot Tea',
        quantity: '',
        price: '40',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'F.C Special Tea',
        category: 'Hot Tea',
        quantity: '',
        price: '70',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Simple Tea',
        category: 'Hot Tea',
        quantity: '',
        price: '50',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Green Tea',
        category: 'Hot Tea',
        quantity: '',
        price: '50',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Pina Colada',
        category: 'Mocktail',
        quantity: '',
        price: '200',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Mint Margarita',
        category: 'Mocktail',
        quantity: '',
        price: '130',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Strawberry Chiller',
        category: 'Mocktail',
        quantity: '',
        price: '140',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Lemon Margarita',
        category: 'Mocktail',
        quantity: '',
        price: '130',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Bule Colada',
        category: 'Mocktail',
        quantity: '',
        price: '220',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Orange Margarita',
        category: 'Mocktail',
        quantity: '',
        price: '130',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Red Vine',
        category: 'Mocktail',
        quantity: '',
        price: '190',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Fruit Collar',
        category: 'Mocktail',
        quantity: '',
        price: '200',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Pink Lady',
        category: 'Mocktail',
        quantity: '',
        price: '200',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
      {
        martId: '5f312d42d9d50a3bebf4611a',
        productName: 'Electric Lemonade',
        category: 'Mocktail',
        quantity: '',
        price: '150',
        net: '0',
        count: '0',
        type: 'single',
        drinks: false,
        regular: false,
        lunchTimeStart: '',
        lunchTimeEnd: '',
      },
    ]);

    return res.json({
      status: '200',
      msg: 'Product added successfully',
    });
  } catch (err) {
    return res.json({
      status: '404',
      error: err.toString(),
      msg: `Looks like something went wrong on our side. Sorry for the inconvenience.`,
    });
  }
}); */

/* router.post('/deleteProducts', async (req, res) => {
  try {
    await Products.deleteMany({ martId: req.body.martId });

    return res.json({
      status: '200',
      msg: 'Products deleted',
    });
  } catch (err) {
    return res.json({
      status: '404',
      error: err.toString(),
      msg: `Looks like something went wrong on our side. Sorry for the inconvenience.`,
    });
  }
}); */

/* router.get('/test', async (req, res) => {
  try {
    // await Products.deleteMany({ martId: '5f841e770a3f9205db17ea38' });

    const products = await Products.find({
      martId: '5f841e770a3f9205db17ea38',
    });

    await Promise.all(
      products.map(async product => {
        if (product.discount === '20') {
          const discountedPrice = ((20 / 100) * product.price).toFixed(2);
          product.discountedPrice = +(product.price - discountedPrice);
        }

        if (product.discount === '10') {
          const discountedPrice = ((10 / 100) * product.price).toFixed(2);
          product.discountedPrice = +(product.price - discountedPrice);
        }

        await product.save();
        return product;
      })
    );

    return res.json('done');
  } catch (err) {
    console.log(err);
    return res.json({
      status: '404',
      error: err.toString(),
      msg: `Looks like something went wrong on our side. Sorry for the inconvenience.`,
    });
  }
}); */

module.exports = router;
